FROM ubuntu:latest



RUN apt-get update && apt-get -y install postgresql wget build-essential default-jdk default-jre tomcat6 apache2

RUN wget http://knb.ecoinformatics.org/software/dist/metacat-src-2.5.1.tar.gz && tar -xvf metacat*.tar.gz
